services:

  www:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./src:/var/www/html
      - ./data:/var/www/data
    ports:
      - 80:80
      - 443:443
    networks:
      - network

networks:
  network:
    driver: bridge